Repository ByteMonk-GCECT/GCECT-APP, pull requests merged in 2022-04, with the labels that each got.

#60 Book Functionalities Screens added
  Ui Ideas/UI.md
Labels: GSSoC22, Level3, UI-suggestion, UI

#65 More Library Management Book screens added
  Ui Ideas/UI.md
Labels: GSSoC22, Level3, UI-suggestion, UI

#50 implemented administration page ui
  .idea/misc.xml
  app/src/main/res/values/strings.xml
Labels: GSSoC22, Level3, UI-implementation, UI

#68 Fixed #67: Text alignment and spacing in Administration Page
  .idea/misc.xml
  app/src/main/res/drawable-v24/faculty_principle_img.png
  app/src/main/res/drawable/dialog_box_rounded_background.xml
  app/src/main/res/layout/administration_ui.xml
  app/src/main/res/layout/fragment_contact_us.xml
  app/src/main/res/layout/history_view_fragment.xml
  app/src/main/res/layout/vision_mission_view_fragment.xml
Labels: GSSoC22, Level2, UI-implementation
