Repository ByteMonk-GCECT/GCECT-APP, pull requests merged in 2022-03, with the labels that each got.

#20 Avoid Using !!(null check) #10
  app/src/main/java/com/gcect/gcectapp/adapters/DownloadViewAdapter.kt
  app/src/main/java/com/gcect/gcectapp/adapters/NavBaseRecyclerAdapter.kt
  app/src/main/java/com/gcect/gcectapp/ui/activity/MainActivity.kt
  app/src/main/java/com/gcect/gcectapp/ui/fragments/EvenSemScheduleFragment.kt
  app/src/main/java/com/gcect/gcectapp/ui/fragments/NoteAddFragment.kt
  app/src/main/java/com/gcect/gcectapp/ui/fragments/NoteShowFragment.kt
  app/src/main/java/com/gcect/gcectapp/ui/fragments/OddSemScheduleFragment.kt
  app/src/main/java/com/gcect/gcectapp/ui/fragments/PdfViewerFragment.kt
  app/src/main/java/com/gcect/gcectapp/ui/fragments/SchedulePdfViewerFragment.kt
Labels: GSSoC22, Level2

#23 History and The Institute Fragment #12
  .idea/misc.xml
  app/src/main/java/com/gcect/gcectapp/ui/fragments/HistoryViewFragment.kt
Labels: GSSoC22, Level3, UI-implementation, UI

#48 Fix #42
  app/src/main/res/drawable/nav_drawer_background.xml
Labels: GSSoC22, Level2, UI

#49 Fix #41
  app/src/main/res/drawable/nav_drawer_background.xml
  app/src/main/res/layout/fragment_home.xml
Labels: GSSoC22, Level2, UI
